### ISSUE TITLE
[Mise en page] Titres soulignés

### ISSUE THREAD

**Issue by gagarine** [t13h37/feedback-jaillot-dettetech#1]
J'avoue que je trouve les titres soulignés difficiles à lire.

![screen shot 2015-02-03 at 15 56 47](https://cloud.githubusercontent.com/assets/164074/6022501/86be3c84-abbd-11e4-850e-b757b1f227cf.png)

J'aime mieux ça déjà...
![screen shot 2015-02-03 at 15 56 47](https://cloud.githubusercontent.com/assets/164074/6022543/d144473a-abbd-11e4-9ca8-e94284b54f8c.png)

**Comment by pouipouidesign** [comment]
Le soulignement qui nous avait semblé indispensable sur ePub (n&b) pourrait en effet ne pas être utilisé dans le PDF, celui-ci bénéficiant de la couleur.
Nous allons donc amender la charte graphique en ce sens pour le PDF.
Merci !
