### ISSUE TITLE
Quelques typos

### ISSUE THREAD

**Issue by nico3333fr** [t13h37/feedback-jaillot-dettetech#10]
Hello,

j'ai trouvé qq petites erreurs pas bien méchantes ;)
- Page 27 (celle-là j'hésite) : "associées à de multiples points de détails amenés" => je mettrai : "associées à de multiples points de **détail** amenés" (dixit http://www.academie-francaise.fr/sites/academie-francaise.fr/files/rectifications_1990.pdf il n'y a pas de "s" à "détail") 
- Page 48 : "valider l'intégration des différent modules" => "valider l'intégration des **différents** modules"
- Page 50 : "vous pouvez comprendre en détails" => "vous pouvez comprendre en **détail**"
- Page 74 : "par Adrian Frutiger sur demande l'aéroport de Paris Charle de Gaulle" => "Par Adrian Frutiger sur demande **de** l'aéroport de **Paris-Charles-de-Gaulle**

Voilou, c'est tout :)

**Comment by pouipouidesign** [comment]
Hello, merci pour la vigilance !
Ces corrections seront incluses dans la prochaine _release_, on fera signe quand elle sera dispo !
