### ISSUE TITLE
Page 13, schema cassé ?

### ISSUE THREAD

**Issue by damienalexandre** [t13h37/feedback-jaillot-dettetech#11]
![image](https://cloud.githubusercontent.com/assets/225704/6883846/1e5a7512-d616-11e4-89ae-7f70295ecd50.png)

Un des labels rouge semble mal placé.

**Comment by bastnic** [comment]
Coucou Damien, 

Il s'agit d'un quadran, donc ligne en haut : délibéré, ligne en bas : involontaire, et pareil pour les colonnes ;).

+
