### ISSUE TITLE
Cohérence affichage des liens

### ISSUE THREAD

**Issue by damienalexandre** [t13h37/feedback-jaillot-dettetech#12]
Parfois les liens hypertexte sont sur le texte lui même,
et parfois, c'est une url lisible entre parenthèse qui suit le texte. 

C'est pas très cohérent, les deux façons de faire sont mixés tout le long. 

Je pense qu'en note de bas de page ou entre parenthèse est le mieux.

**Comment by pouipouidesign** [comment]
Bonjour, c'est pas faux :)
On voit pour améliorer ça dans la prochaine version !
