### ISSUE TITLE
Diverses coquilles

### ISSUE THREAD

**Issue by P45QU10U** [t13h37/feedback-jaillot-dettetech#13]
page 9 
La réunion est orchestré\* par le chef de projet
- orchestrée

page 16
• 21 maintenant (pour la refactorisation), 0 plus tard (pour la
permission); Dans ce scénario, l’entreprise n’as\* pas ajouté 5 clients à
son portfolio de suite, et l’argent arrivera plus tard;
- n’a

page 27
Ce sujet a rapidement été clos car je ne m’estimais pas
capable de faire quelques\* chose de correct et que la problématique de
modération n’arrive de toute façon qu’une fois qu’il y a du contenu…
- quelque

page 44
Voici quelques exemples de mesures qui ont permi\* de sauver des situations
qui auraient pu traîner bien plus longtemps : […] C’est la combinaison des différents facteurs qui nous a permi\* de le détecter.
- permis (× 2)

page 47
• mutualiser la responsabilité, notamment grâce les\* revues de code.
- aux ?

page 49
Il aurai\* donc mieux valu avant tout écrire une suite de tests comprenant les
scénarios que l’on allait rencontrer. Exécuter cette suite de tests pendant le
développement aurai\* ainsi ensuite permis de vérifier la validité du code.
- aurait (× 2)

Page 65
Pragmatique dans l’âme, j’ai alors\* cherché alors\* un moyen de contourner le
problème. Apparemment, l’intégration base de données de Search API
permettait dorénavant de faire des requêtes « OU », ce qu’il n’était pas
capable de faire précédemment.
- répétition ?

**Comment by bastnic** [comment]
![Merci !](http://media2.giphy.com/media/4lpctAAV9Azpm/giphy.gif)

**Comment by pouipouidesign** [comment]
Merci pour la vigilance, on s'en occupe dans la prochaine version ! :)
