### ISSUE TITLE
Coquille(s)

### ISSUE THREAD

**Issue by welcoMattic** [t13h37/feedback-jaillot-dettetech#14]
Page 55 :

D’autres fois, il faut revenir sur ceux-ci pour améliorer la qualité du projet,
quitte à en reprendre de **nouveaux** une fois les précédents raccourcis
remboursés.

-> nouveau

**Comment by pouipouidesign** [comment]
Bonjour,
En l'occurence, il ne s'agit pas d'une erreur, puisqu'il est question de reprendre de nouveaux "raccourcis".
Merci quand même pour la remarque et la vigilance ! :)

**Comment by welcoMattic** [comment]
@pouipouidesign Peut-être retirer `une fois` alors ? Ça clarifie la phrase ;)
