### ISSUE TITLE
La confiance n'exclut pas le contrôle...

### ISSUE THREAD

**Issue by macintoshplus** [t13h37/feedback-jaillot-dettetech#18]
Bonjour,

Merci pour votre travail pour la réalisation de ce livre. J’ai une remarque concernant une phrase malheureuse utilisé dans le livre.

Il est mentionné "La confiance n'exclut pas le contrôle" en introduction de la revue de code.
Cette phrase me semble maladroite car le « contrôle » exclut la confiance et induit une méfiance sur le travail effectué par un pair. Par opposition la revue nécessite une confiance mutuelle entre les développeurs afin que la revue soit menée en toute bienveillance avec une large part de discussion et sans biais.

Un jour ou l’autre les rôles seront inversés pour une autre revue de code et sans la confiance, la situation peut vite devenir tendue.

Prenons un exemple, mon commentaire pourrait être assimilé à une revue de code. En achetant le livre j’ai montré que j’avais confiance en l’auteur sur le sujet évoqué. Maintenant si l’auteur accepte les remarques (via ce dépôt) c’est qu’il me fait confiance.
Il attend de mes remarques qu’elles soient bienveillantes et que nous puisons avoir une discussion sur le sujet présent. De mon côté j’attends de l’auteur une ouverture d’esprit permettant le dialogue sur mes remarques.
A l’inverse une remarque acerbe de ma part ou un retour désagréable de la part de l’auteur brise la confiance et par conséquent le dialogue. Cela aura également des répercussions plus tard. Une situation similaire dans une équipe peut aboutir sur un échec.

Dans l’attente de vous lire, je vous souhaite une bonne journée.

**Comment by bastnic** [comment]
Bonsoir Jean-Baptiste, 

Merci beaucoup d'avoir acheté notre livre et merci encore plus d'avoir pris le temps de partager votre retour. C'est en effet très dur pour un auteur de ne pas avoir de retour sur ce qui peut-être mal interprété ou mal compris (je préfère de loin les discussions en direct...).

Sur ce point précis, je vais essayer de vous répondre en expliquant plus en détails ce que j'entends par "la confiance n'exclut pas le contrôle".

TL;DR: contrôle = vérification (bienveillante)

A premier lieu je me contrôle moi même. Je pense avoir codé quelque chose, je vérifie que j'ai pas touché à autre chose (ça m'est déjà arrivé de laisser des `die;` traîner et de stage un peu violemment en oubliant de vérifier). Je peux également penser avoir fixé tous les cas d'usage mais un collègue va lire ça et penser à un autre. Les tests unitaires sont une sorte de contrôle, j'ai codé ma fonctionnalité, les tests existants vont contrôler que je n'ai rien cassé. Mes collègues vont contrôler la compréhension de ma documentation au spectre de leurs connaissances, "super merci Bastien pour cette feature qui a l'air top, j'ai juste un doute, je ne comprends pas ce changement, peux-tu m'éclairer stp ?" (si cette personne ne comprend pas, de fortes chances que ce ne soit pas clair du tout, donc nécessite un peu de travail).

Dans un autre environnement, admettons que je doive planter un pieu perpendiculairement au sol, je l'ai fait 1000x et j'ai confiance en moi, je vais quand même prendre une équerre pour contrôler que j'ai bon.

Pour résumer, cette notion de "contrôle" n'a vraiment aucune connotation négative, ni méfiance. Nous sommes tous co-contributeur d'une œuvre commune et je ne prendrais pas comme une attaque personnelle que l'on me fasse des retours me demandant des modifications. 
Au contraire, ils s'impliquent et je trouve que c'est excellent.

Du coup, je vois que nous ne partageons pas la même compréhension du mot contrôle. 
1/ est-ce que cette explication est plus claire sur mes intentions ? 
2/ est-ce que vous pensez qu'il est nécessaire que j'ajoute plus d'explication dans le livre ? 
3/ est-ce que vous pensez que ces explications sont assez claires ?

Merci encore.

**Comment by macintoshplus** [comment]
Merci d'avoir pris le temps de me répondre. J'aime pouvoir discuter quand quelque chose n'est pas comprise.

Je comprend votre point de vue et vos explications sont claires. Je ne vous jette absolument pas la pierre car ce n'est pas la première fois que j'entends cette expression et que j'en discute ;-)

J'aimerai maintenant vous proposer un autre point de vue du mot `contrôle` que nous connaissons tous (à minima entendu parlé) et qui ne renvoie en rien à la bienveillance et à la confiance :
- les contrôles qualités
- les contrôles des titres de transport
- les contrôles fiscaux
- les contrôles douaniers
- les contrôles aux aéroports
- les contrôles de la saisie de l'utilisateur
- ...

Tout ces cas ont un point commun, la sanction en cas d'échec et un côté très autoritaire lié au contrôle. Et dans certain cas le contrôlé est présumé fautif. La sanction est plus ou moins forte selon les cas.

Voici ce que dit le petit Larousse sur ce mot : https://www.larousse.fr/dictionnaires/francais/contr%C3%B4le/18932

Alors que dans le code review c'est l’opposé. A mon avis les mots `confiance` et `contrôle` sont antinomique dans cette expression.

Je trouve le terme de `revue de code` tout à fait juste et qui ne renvoie en rien à une potentielle sanction.
Du coup l'expression deviendrai `la confiance n’exclue pas la revue de code`.

Pour répondre à vos questions, oui, une explication me semble nécessaire pour éclairer sur votre intention première.

Merci pour cet échange.

**Comment by bastnic** [comment]
Je comprends mieux votre problème sur le mot contrôle, même si je ne le partage pas. 

Pour désambiguïser, effectivement `la confiance n’exclue pas la revue de code` pourrait aller, mais j'ai l'impression que comme c'est censé expliquer la revue de code, l'inclure dans la phrase bizarre. Peut-être "la confiance n'exclue pas une vérification bienveillante".

**Comment by macintoshplus** [comment]
Effectivement, je trouvais également la phrase un peu étrange mais celle ci "la confiance n'exclue pas une vérification bienveillante" me semble beaucoup plus adaptée.

Je vous laisse juge de la modification à apporter ou non à votre livre 😉 Pour ma part, je suis content de cette discutions franche et bienveillante. J'espère que l'on se rencontrera un jour. Peut être au détour d'une conférence 😀
