### ISSUE TITLE
Mauvais page break

### ISSUE THREAD

**Issue by gagarine** [t13h37/feedback-jaillot-dettetech#2]
Retour de paragraphe sur un mot. Mieux vaut mettre l'image tout seul sur la page du coup.

![screen shot 2015-02-03 at 17 54 17](https://cloud.githubusercontent.com/assets/164074/6024752/c5aa14b2-abcd-11e4-8da6-0fb6332b9696.png)

**Comment by loicm** [comment]
En effet bien vu. On va faire attention à ça lors de la génération pdf de la 1.1
