### ISSUE TITLE
Détailler l'acronyme anglais

### ISSUE THREAD

**Issue by brice** [t13h37/feedback-jaillot-dettetech#4]
Peut-être faudrait il préciser ce que MVP veut dire     

> Traditionnellement, on utilise la notion de Produit Minimum Viable (MVP)

Proposition 

> Traditionnellement, on utilise la notion de Produit Minimum Viable (ou MVP soit Minimum Viable Product en VO)

**Comment by gagarine** [comment]
> Traditionnellement, on utilise la notion de Produit Minimum Viable (Couramment connu sous l'acronyme anglais MVP soit Minimum Viable Product).

Le VO n'étant pas forcément anglais et expliquer un acronyme en ajoutant un acronyme... ;)

**Comment by loicm** [comment]
Merci de vos retours. Du coup on vient d'impacter une modification dans nos sources :

> Traditionnellement, on utilise la notion de Produit Minimum Viable (en anglais MVP, soit Minimum Viable Product)
